"""
Ensures the data/ directory and seed JSON files exist at startup.
Safe to call on every boot — only writes if a file is missing.
"""
import json
import os

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")

SEED = {   'invoices.json': {   '9876543210': [   {   'invoice_id': 'INV-20261101',
                                               'billing_period': '01 May 2026 – 30 May 2026',
                                               'due_date': '2026-06-04',
                                               'total_amount': 1249,
                                               'status': 'unpaid',
                                               'line_items': [   {'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'},
                                                                 {'description': 'SAARC roaming pack — 14 days', 'amount': 299, 'type': 'addon_charge', 'activated_on': '2026-05-14'},
                                                                 {   'description': 'Excess data — 8.4 GB beyond daily limit',
                                                                     'amount': 251,
                                                                     'type': 'excess_usage',
                                                                     'usage_dates': ['2024-11-11', '2024-11-12']}]},
                                           {   'invoice_id': 'INV-20261001',
                                               'billing_period': '31 Mar 2026 – 30 Apr 2026',
                                               'due_date': '2026-05-05',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260901',
                                               'billing_period': '01 Mar 2026 – 30 Mar 2026',
                                               'due_date': '2026-04-04',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260801',
                                               'billing_period': '29 Jan 2026 – 28 Feb 2026',
                                               'due_date': '2026-03-05',
                                               'total_amount': 999,
                                               'status': 'paid',
                                               'line_items': [   {'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'},
                                                                 {'description': 'International roaming pack — 7 days', 'amount': 300, 'type': 'addon_charge', 'activated_on': '2026-02-07'}]},
                                           {   'invoice_id': 'INV-20260701',
                                               'billing_period': '29 Dec 2025 – 28 Jan 2026',
                                               'due_date': '2026-02-02',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260601',
                                               'billing_period': '29 Nov 2025 – 28 Dec 2025',
                                               'due_date': '2026-01-02',
                                               'total_amount': 823,
                                               'status': 'paid',
                                               'line_items': [   {'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'},
                                                                 {   'description': 'Excess data — 3.1 GB beyond daily limit',
                                                                     'amount': 124,
                                                                     'type': 'excess_usage',
                                                                     'usage_dates': ['2024-06-18', '2024-06-19']}]},
                                           {   'invoice_id': 'INV-20260501',
                                               'billing_period': '29 Oct 2025 – 28 Nov 2025',
                                               'due_date': '2025-12-03',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260401',
                                               'billing_period': '29 Sep 2025 – 28 Oct 2025',
                                               'due_date': '2025-11-02',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260301',
                                               'billing_period': '29 Aug 2025 – 28 Sep 2025',
                                               'due_date': '2025-10-03',
                                               'total_amount': 1098,
                                               'status': 'paid',
                                               'line_items': [   {'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'},
                                                                 {'description': 'Premium OTT bundle — 1 month', 'amount': 399, 'type': 'addon_charge', 'activated_on': '2025-08-29'}]},
                                           {   'invoice_id': 'INV-20260201',
                                               'billing_period': '31 Jul 2025 – 28 Aug 2025',
                                               'due_date': '2025-09-02',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260101',
                                               'billing_period': '30 Jun 2025 – 30 Jul 2025',
                                               'due_date': '2025-08-04',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20231201',
                                               'billing_period': '30 May 2025 – 29 Jun 2025',
                                               'due_date': '2025-07-04',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]}],
                         '7406179387': [   {   'invoice_id': 'INV-20261101',
                                               'billing_period': '01 May 2026 – 30 May 2026',
                                               'due_date': '2026-06-04',
                                               'total_amount': 1249,
                                               'status': 'unpaid',
                                               'line_items': [   {'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'},
                                                                 {'description': 'SAARC roaming pack — 14 days', 'amount': 299, 'type': 'addon_charge', 'activated_on': '2026-05-14'},
                                                                 {   'description': 'Excess data — 8.4 GB beyond daily limit',
                                                                     'amount': 251,
                                                                     'type': 'excess_usage',
                                                                     'usage_dates': ['2024-11-11', '2024-11-12']}]},
                                           {   'invoice_id': 'INV-20261001',
                                               'billing_period': '31 Mar 2026 – 30 Apr 2026',
                                               'due_date': '2026-05-05',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260901',
                                               'billing_period': '01 Mar 2026 – 30 Mar 2026',
                                               'due_date': '2026-04-04',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260801',
                                               'billing_period': '29 Jan 2026 – 28 Feb 2026',
                                               'due_date': '2026-03-05',
                                               'total_amount': 999,
                                               'status': 'paid',
                                               'line_items': [   {'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'},
                                                                 {'description': 'International roaming pack — 7 days', 'amount': 300, 'type': 'addon_charge', 'activated_on': '2026-02-07'}]},
                                           {   'invoice_id': 'INV-20260701',
                                               'billing_period': '29 Dec 2025 – 28 Jan 2026',
                                               'due_date': '2026-02-02',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260601',
                                               'billing_period': '29 Nov 2025 – 28 Dec 2025',
                                               'due_date': '2026-01-02',
                                               'total_amount': 823,
                                               'status': 'paid',
                                               'line_items': [   {'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'},
                                                                 {   'description': 'Excess data — 3.1 GB beyond daily limit',
                                                                     'amount': 124,
                                                                     'type': 'excess_usage',
                                                                     'usage_dates': ['2024-06-18', '2024-06-19']}]},
                                           {   'invoice_id': 'INV-20260501',
                                               'billing_period': '29 Oct 2025 – 28 Nov 2025',
                                               'due_date': '2025-12-03',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260401',
                                               'billing_period': '29 Sep 2025 – 28 Oct 2025',
                                               'due_date': '2025-11-02',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260301',
                                               'billing_period': '29 Aug 2025 – 28 Sep 2025',
                                               'due_date': '2025-10-03',
                                               'total_amount': 1098,
                                               'status': 'paid',
                                               'line_items': [   {'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'},
                                                                 {'description': 'Premium OTT bundle — 1 month', 'amount': 399, 'type': 'addon_charge', 'activated_on': '2025-08-29'}]},
                                           {   'invoice_id': 'INV-20260201',
                                               'billing_period': '31 Jul 2025 – 28 Aug 2025',
                                               'due_date': '2025-09-02',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260101',
                                               'billing_period': '30 Jun 2025 – 30 Jul 2025',
                                               'due_date': '2025-08-04',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20231201',
                                               'billing_period': '30 May 2025 – 29 Jun 2025',
                                               'due_date': '2025-07-04',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]}],
                         '9858509904': [   {   'invoice_id': 'INV-20261101',
                                               'billing_period': '01 May 2026 – 30 May 2026',
                                               'due_date': '2026-06-04',
                                               'total_amount': 1249,
                                               'status': 'unpaid',
                                               'line_items': [   {'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'},
                                                                 {'description': 'SAARC roaming pack — 14 days', 'amount': 299, 'type': 'addon_charge', 'activated_on': '2026-05-14'},
                                                                 {   'description': 'Excess data — 8.4 GB beyond daily limit',
                                                                     'amount': 251,
                                                                     'type': 'excess_usage',
                                                                     'usage_dates': ['2024-11-11', '2024-11-12']}]},
                                           {   'invoice_id': 'INV-20261001',
                                               'billing_period': '31 Mar 2026 – 30 Apr 2026',
                                               'due_date': '2026-05-05',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260901',
                                               'billing_period': '01 Mar 2026 – 30 Mar 2026',
                                               'due_date': '2026-04-04',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260801',
                                               'billing_period': '29 Jan 2026 – 28 Feb 2026',
                                               'due_date': '2026-03-05',
                                               'total_amount': 999,
                                               'status': 'paid',
                                               'line_items': [   {'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'},
                                                                 {'description': 'International roaming pack — 7 days', 'amount': 300, 'type': 'addon_charge', 'activated_on': '2026-02-07'}]},
                                           {   'invoice_id': 'INV-20260701',
                                               'billing_period': '29 Dec 2025 – 28 Jan 2026',
                                               'due_date': '2026-02-02',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260601',
                                               'billing_period': '29 Nov 2025 – 28 Dec 2025',
                                               'due_date': '2026-01-02',
                                               'total_amount': 823,
                                               'status': 'paid',
                                               'line_items': [   {'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'},
                                                                 {   'description': 'Excess data — 3.1 GB beyond daily limit',
                                                                     'amount': 124,
                                                                     'type': 'excess_usage',
                                                                     'usage_dates': ['2024-06-18', '2024-06-19']}]},
                                           {   'invoice_id': 'INV-20260501',
                                               'billing_period': '29 Oct 2025 – 28 Nov 2025',
                                               'due_date': '2025-12-03',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260401',
                                               'billing_period': '29 Sep 2025 – 28 Oct 2025',
                                               'due_date': '2025-11-02',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260301',
                                               'billing_period': '29 Aug 2025 – 28 Sep 2025',
                                               'due_date': '2025-10-03',
                                               'total_amount': 1098,
                                               'status': 'paid',
                                               'line_items': [   {'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'},
                                                                 {'description': 'Premium OTT bundle — 1 month', 'amount': 399, 'type': 'addon_charge', 'activated_on': '2025-08-29'}]},
                                           {   'invoice_id': 'INV-20260201',
                                               'billing_period': '31 Jul 2025 – 28 Aug 2025',
                                               'due_date': '2025-09-02',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20260101',
                                               'billing_period': '30 Jun 2025 – 30 Jul 2025',
                                               'due_date': '2025-08-04',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]},
                                           {   'invoice_id': 'INV-20231201',
                                               'billing_period': '30 May 2025 – 29 Jun 2025',
                                               'due_date': '2025-07-04',
                                               'total_amount': 699,
                                               'status': 'paid',
                                               'line_items': [{'description': 'Monthly plan — ₹699 postpaid', 'amount': 699, 'type': 'plan_charge'}]}]},
    'activation_log.json': {   '9876543210': [   {   'event_id': 'EVT-9921',
                                                     'service': 'SAARC roaming pack',
                                                     'action': 'activated',
                                                     'triggered_by': 'system_auto',
                                                     'timestamp': '2026-05-14T09:32:11Z',
                                                     'channel': 'automated_rule',
                                                     'customer_initiated': False},
                                                 {   'event_id': 'EVT-9890',
                                                     'service': 'Monthly plan — ₹699',
                                                     'action': 'renewed',
                                                     'triggered_by': 'customer',
                                                     'timestamp': '2026-05-01T00:00:00Z',
                                                     'channel': 'self_service_app',
                                                     'customer_initiated': True}],
                               '7406179387': [   {   'event_id': 'EVT-9921',
                                                     'service': 'SAARC roaming pack',
                                                     'action': 'activated',
                                                     'triggered_by': 'system_auto',
                                                     'timestamp': '2026-05-14T09:32:11Z',
                                                     'channel': 'automated_rule',
                                                     'customer_initiated': False},
                                                 {   'event_id': 'EVT-9890',
                                                     'service': 'Monthly plan — ₹699',
                                                     'action': 'renewed',
                                                     'triggered_by': 'customer',
                                                     'timestamp': '2026-05-01T00:00:00Z',
                                                     'channel': 'self_service_app',
                                                     'customer_initiated': True}],
                               '9858509904': [   {   'event_id': 'EVT-9921',
                                                     'service': 'SAARC roaming pack',
                                                     'action': 'activated',
                                                     'triggered_by': 'system_auto',
                                                     'timestamp': '2026-05-14T09:32:11Z',
                                                     'channel': 'automated_rule',
                                                     'customer_initiated': False},
                                                 {   'event_id': 'EVT-9890',
                                                     'service': 'Monthly plan — ₹699',
                                                     'action': 'renewed',
                                                     'triggered_by': 'customer',
                                                     'timestamp': '2026-05-01T00:00:00Z',
                                                     'channel': 'self_service_app',
                                                     'customer_initiated': True}]},
    'account_balance.json': {   '9876543210': {'current_balance': 1249.0, 'currency': 'INR', 'last_payment': {'amount': 699, 'date': '2026-04-04', 'method': 'UPI'}, 'next_due_date': '2026-06-04', 'plan_name': '₹699 Postpaid Premium'},
                                '7406179387': {'current_balance': 1249.0, 'currency': 'INR', 'last_payment': {'amount': 699, 'date': '2026-04-04', 'method': 'UPI'}, 'next_due_date': '2026-06-04', 'plan_name': '₹699 Postpaid Premium'},
                                '9858509904': {'current_balance': 1249.0, 'currency': 'INR', 'last_payment': {'amount': 699, 'date': '2026-04-04', 'method': 'UPI'}, 'next_due_date': '2026-06-04', 'plan_name': '₹699 Postpaid Premium'}},
    'usage_history.json': {   '9876543210': [   {'date': '2026-05-01', 'data_used_gb': 1.4, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 45, 'sms_count': 2},
                                                {'date': '2026-05-02', 'data_used_gb': 0.9, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 30, 'sms_count': 1},
                                                {'date': '2026-05-03', 'data_used_gb': 1.1, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 55, 'sms_count': 4},
                                                {'date': '2026-05-04', 'data_used_gb': 1.7, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 38, 'sms_count': 0},
                                                {'date': '2026-05-05', 'data_used_gb': 0.5, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 20, 'sms_count': 3},
                                                {'date': '2026-05-06', 'data_used_gb': 1.9, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 90, 'sms_count': 6},
                                                {'date': '2026-05-07', 'data_used_gb': 1.2, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 60, 'sms_count': 2},
                                                {'date': '2026-05-08', 'data_used_gb': 0.8, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 25, 'sms_count': 1},
                                                {'date': '2026-05-09', 'data_used_gb': 1.5, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 70, 'sms_count': 5},
                                                {'date': '2026-05-10', 'data_used_gb': 1.8, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 50, 'sms_count': 2},
                                                {'date': '2026-05-11', 'data_used_gb': 4.2, 'daily_limit_gb': 2.0, 'excess_gb': 2.2, 'calls_minutes': 84, 'sms_count': 5},
                                                {'date': '2026-05-12', 'data_used_gb': 3.6, 'daily_limit_gb': 2.0, 'excess_gb': 1.6, 'calls_minutes': 112, 'sms_count': 3},
                                                {'date': '2026-05-13', 'data_used_gb': 1.8, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 67, 'sms_count': 8},
                                                {'date': '2026-05-14', 'data_used_gb': 1.3, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 40, 'sms_count': 1},
                                                {'date': '2026-05-15', 'data_used_gb': 0.7, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 33, 'sms_count': 2}],
                              '7406179387': [   {'date': '2026-05-01', 'data_used_gb': 1.4, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 45, 'sms_count': 2},
                                                {'date': '2026-05-02', 'data_used_gb': 0.9, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 30, 'sms_count': 1},
                                                {'date': '2026-05-03', 'data_used_gb': 1.1, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 55, 'sms_count': 4},
                                                {'date': '2026-05-04', 'data_used_gb': 1.7, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 38, 'sms_count': 0},
                                                {'date': '2026-05-05', 'data_used_gb': 0.5, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 20, 'sms_count': 3},
                                                {'date': '2026-05-06', 'data_used_gb': 1.9, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 90, 'sms_count': 6},
                                                {'date': '2026-05-07', 'data_used_gb': 1.2, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 60, 'sms_count': 2},
                                                {'date': '2026-05-08', 'data_used_gb': 0.8, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 25, 'sms_count': 1},
                                                {'date': '2026-05-09', 'data_used_gb': 1.5, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 70, 'sms_count': 5},
                                                {'date': '2026-05-10', 'data_used_gb': 1.8, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 50, 'sms_count': 2},
                                                {'date': '2026-05-11', 'data_used_gb': 4.2, 'daily_limit_gb': 2.0, 'excess_gb': 2.2, 'calls_minutes': 84, 'sms_count': 5},
                                                {'date': '2026-05-12', 'data_used_gb': 3.6, 'daily_limit_gb': 2.0, 'excess_gb': 1.6, 'calls_minutes': 112, 'sms_count': 3},
                                                {'date': '2026-05-13', 'data_used_gb': 1.8, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 67, 'sms_count': 8},
                                                {'date': '2026-05-14', 'data_used_gb': 1.3, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 40, 'sms_count': 1},
                                                {'date': '2026-05-15', 'data_used_gb': 0.7, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 33, 'sms_count': 2}],
                              '9858509904': [   {'date': '2026-05-01', 'data_used_gb': 1.4, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 45, 'sms_count': 2},
                                                {'date': '2026-05-02', 'data_used_gb': 0.9, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 30, 'sms_count': 1},
                                                {'date': '2026-05-03', 'data_used_gb': 1.1, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 55, 'sms_count': 4},
                                                {'date': '2026-05-04', 'data_used_gb': 1.7, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 38, 'sms_count': 0},
                                                {'date': '2026-05-05', 'data_used_gb': 0.5, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 20, 'sms_count': 3},
                                                {'date': '2026-05-06', 'data_used_gb': 1.9, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 90, 'sms_count': 6},
                                                {'date': '2026-05-07', 'data_used_gb': 1.2, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 60, 'sms_count': 2},
                                                {'date': '2026-05-08', 'data_used_gb': 0.8, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 25, 'sms_count': 1},
                                                {'date': '2026-05-09', 'data_used_gb': 1.5, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 70, 'sms_count': 5},
                                                {'date': '2026-05-10', 'data_used_gb': 1.8, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 50, 'sms_count': 2},
                                                {'date': '2026-05-11', 'data_used_gb': 4.2, 'daily_limit_gb': 2.0, 'excess_gb': 2.2, 'calls_minutes': 84, 'sms_count': 5},
                                                {'date': '2026-05-12', 'data_used_gb': 3.6, 'daily_limit_gb': 2.0, 'excess_gb': 1.6, 'calls_minutes': 112, 'sms_count': 3},
                                                {'date': '2026-05-13', 'data_used_gb': 1.8, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 67, 'sms_count': 8},
                                                {'date': '2026-05-14', 'data_used_gb': 1.3, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 40, 'sms_count': 1},
                                                {'date': '2026-05-15', 'data_used_gb': 0.7, 'daily_limit_gb': 2.0, 'excess_gb': 0, 'calls_minutes': 33, 'sms_count': 2}]},
    'tickets.json': [
        {
            'ticket_id': 'BTC-88101',
            'created_at': '2026-05-14T10:30:00Z',
            'mobile_number': '9876543210',
            'type': 'billing_dispute',
            'issue_summary': 'Excess data charge inquiry for May 12.',
            'root_cause': 'customer_unaware_of_usage',
            'action_taken': 'Explained 5G usage consumption. Customer satisfied.',
            'credit_amount': 0.0,
            'credit_id': None,
            'priority': 'low',
            'resolution_status': 'resolved',
            'raised_by': 'aarav_billing_agent'
        },
        {
            'ticket_id': 'BTC-88102',
            'created_at': '2026-05-15T09:15:00Z',
            'mobile_number': '7406179387',
            'type': 'service_request',
            'issue_summary': 'International roaming pack not working in Singapore.',
            'root_cause': 'network_handshake_delay',
            'action_taken': 'Manual network refresh pushed to SIM. Roaming active now.',
            'credit_amount': 0.0,
            'credit_id': None,
            'priority': 'high',
            'resolution_status': 'resolved',
            'raised_by': 'manual_support'
        }
    ]
}

def ensure_seed_data(force=False):
    os.makedirs(DATA_DIR, exist_ok=True)
    for filename, default in SEED.items():
        path = os.path.join(DATA_DIR, filename)
        if force or not os.path.exists(path):
            with open(path, "w", encoding="utf-8") as f:
                json.dump(default, f, indent=2, ensure_ascii=False)
